# fly.toml file generated for the-worry-list on 2023-04-06T14:13:49+01:00

app = "the-worry-list"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "lhr"
processes = []

[build]
  image = "bendickman/the-worry-list:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
